"""add usage accounting to executions

Revision ID: 599a6583b58a
Revises: 97138572bd33
Create Date: 2026-09-10 19:01:23.234216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "599a6583b58a"
down_revision: Union[str, Sequence[str], None] = "97138572bd33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("prompt_tokens", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("completion_tokens", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("total_tokens", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("llm_calls", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("latency_ms", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("cost_usd", sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column("usage_by_model", sa.JSON(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_executions_created_at"),
            ["created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_executions_created_at"))
        batch_op.drop_column("usage_by_model")
        batch_op.drop_column("cost_usd")
        batch_op.drop_column("latency_ms")
        batch_op.drop_column("llm_calls")
        batch_op.drop_column("total_tokens")
        batch_op.drop_column("completion_tokens")
        batch_op.drop_column("prompt_tokens")

    # ### end Alembic commands ###
